
spring:
  datasource:
    url: jdbc:h2:~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format: true

  devtools:
    # ?? ???? ??? ?? ? ?? ????.
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .xhtml
    # thymeleaf? ?? ??? ??? ???. false ??(???? true)
    cache: false
    # templates ????? ??? ??? ??? ??, ??? ??? ?????.
    check-template-location: true

logging:
  level:
    org.hibernate.SQL: debug







